# Default Configuration: https://jekyllrb.com/docs/configuration/default/
# Font Matter Defaults:  https://jekyllrb.com/docs/configuration/front-matter-defaults/
# Configuration Options: https://jekyllrb.com/docs/configuration/options/

lsi: false # Produce an index for related posts. Requires the classifier-reborn plugin. -> https://jekyllrb.com/docs/configuration/options/#build-command-options
safe: true # Disable non-whitelisted plugins, caching to disk, and ignore symbolic links. -> https://jekyllrb.com/docs/configuration/options/#build-command-options

# Exclude files that do not need to be rendered and included in the final build of the website
exclude:
  - github-actions
  - docker-compose.yml
  - package-lock.json
  - _projects
  - _guide-pages
  - _design-system
  - _program-areas
  - surveys
  - test
  - google-apps-scripts
  - redirections

source: . # Change the directory where Jekyll will read files

title: BIBALANCE
email: z.li@bcbl.eu
description: BIBALANCE is a European Research Council project studying how children’s reading and their brain.

baseurl: ""
url: https://peter-ziyuan.github.io/website-BIBALANCE



# When/Before creating a new collections remember these two pieces of advice and ask yourself. Should you?
#    1. Collections are a great way to group related content like members of a team or talks at a conference. [https://jekyllrb.com/docs/collections/]
#    2. Collection — Will have its own page, URLs, and possibly an index page. [https://gist.github.com/akibrhast/31c7bb723d80e9efe3d28f619ef0798d]

# Please refer to the documentation here[https://jekyllrb.com/docs/configuration/front-matter-defaults/] before modifying defaults
# The settings below reads as so
#     - Everything within the `pages` directory that is of type `pages` will be rendered using the `default` layout as defined ins `_layouts/default.html`
#     - Everything within the `_projects` directory that is of type `projects` will be rendered using the `project` layout as defined ins `_layouts/project.html`
#     - Everything within the `_guide-pages` directory that is of type `guide-pages` will be rendered using the `guide-pages` layout as defined ins `_layouts/guide-pages.html`



plugins:
  - jekyll-sitemap


